import React from "react";

export default function Abite() {
    return (
        <div className="p-3 mb-2 bg-body">
            <h2>Abite this app</h2>
            <p>
                Potters Ipsum a placeholder text generator similar to lorem ipsum, except it generates text in an
                unusual English dialect from North Staffordshire, as documented in the "Jabez" stories by
                A. Scott (real name Wilfred Bloor) published in the 1960s and 70s.  The text is generated by
                selecting random sentences from a collection of stories called "The Second Book of Jabez",
                which was self-published in 1973.  The stories are based on true events that occurred during
                the early 19th and late 18th century in and around the hamlet of Scot Hay.  You can find the
                original sources and other works of Wilfred Bloor in the links below.
            </p>
            <p>
                <em>
                    For educational use only.  This website operates without ads, user data collection, or commercial
                    activity of any kind.  Enjoy theesel!
                </em>
            </p>
        </div>
    );
}